name: Multiplatform Main

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.html'
      - 'media/**'
      - 'content/**'
      - 'docs/**'

concurrency:
  group: main
  cancel-in-progress: false

env:
  MONSTER_COMPENDIUM_KEYSTORE_PASSWORD: ${{ secrets.MONSTER_COMPENDIUM_KEYSTORE_PASSWORD }}
  AMPLITUDE_API_KEY: ${{ secrets.AMPLITUDE_API_KEY }}
  AMPLITUDE_SANDBOX_API_KEY: ${{ secrets.AMPLITUDE_SANDBOX_API_KEY }}
  REVENUE_CAT_ANDROID_API_KEY: ${{ secrets.REVENUE_CAT_ANDROID_API_KEY }}
  REVENUE_CAT_IOS_API_KEY: ${{ secrets.REVENUE_CAT_IOS_API_KEY }}
  REVENUE_CAT_SANDBOX_API_KEY: ${{ secrets.REVENUE_CAT_SANDBOX_API_KEY }}

jobs:
  android-build:
    name: Android Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.5.0

      - uses: ./.github/actions/setup-gradle

      - name: Build with Gradle
        run: ./gradlew bundleRelease

      - name: Verify database migration
        run: chmod +x ./scripts/sqldelight/verifyDatabaseMigration && ./scripts/sqldelight/verifyDatabaseMigration

      - uses: ./.github/actions/upload-test-report

  android-dev-distribution:
    name: Android APK Dev Distribution
    uses: ./.github/workflows/AndroidDevDistribution.yml
    secrets: inherit
